# DigitalOcean App Platform Configuration
name: license-server

services:
  - name: api
    dockerfile_path: Dockerfile
    github:
      repo: YOUR_GITHUB_USERNAME/license-server
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    envs:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ADMIN_EMAIL
        scope: RUN_TIME
        value: admin@yourdomain.com
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        value: sqlite+aiosqlite:///./licenses.db
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: '["https://yourdomain.com"]'

# For managed database (optional, +$15/month):
# databases:
#   - name: license-db
#     engine: PG
#     version: "15"
#     size: db-s-dev-database
